services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATASOURCE}
    ports:
      - "5432:5432"
    volumes:
      - socialappdb:/var/lib/postgresql/data

volumes:
  socialappdb: